### ISSUE TITLE
Error in creating search responses

### ISSUE THREAD

**Issue by Pretzelential** [kiranshila/Doplarr#67]
**Expected behavior**
I expect to be able to request a movie from my discord bot but always receive "Error in creating search responses"

**Logs**
Please copy out the log in it's entirety, please make sure to hide any potential secrets/API keys - although they should be censored via the logging program.
```
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/


Brought to you by linuxserver.io
-------------------------------------

To support the app dev(s) visit:
kiranshila: https://github.com/sponsors/kiranshila

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    1000
User gid:    100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 19-armless: executing... 
[cont-init.d] 19-armless: exited 0.
[cont-init.d] 30-config: executing... 
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
2022-03-17T17:31:50.803Z 024ddd456b72 INFO [doplarr.config:63] - Configuration is valid
2022-03-17T17:31:51.359Z 024ddd456b72 INFO [discljord.messaging.impl:?] - Starting messaging process
2022-03-17T17:31:51.368Z 024ddd456b72 INFO [discljord.connections.impl:?] - Connecting shard 0
2022-03-17 13:31:51.408:INFO::async-dispatch-4: Logging initialized @3920ms to org.eclipse.jetty.util.log.StdErrLog
2022-03-17T17:31:52.077Z 024ddd456b72 INFO [doplarr.core:38] - Discord connection successful
2022-03-17T17:31:52.086Z 024ddd456b72 INFO [doplarr.core:43] - Connected to guild
2022-03-17T17:31:52.219Z 024ddd456b72 INFO [doplarr.core:49] - Setting role id. Reminder, even the server owner needs this role.
2022-03-17T17:32:08.795Z 024ddd456b72 INFO [doplarr.interaction-state-machine:28] - Performing search for movie Rambo
2022-03-17T17:32:09.748Z 024ddd456b72 FATAL [doplarr.interaction-state-machine:41] - Error in creating search responses
                               java.lang.Thread.run              Thread.java:  831
 java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  630
  java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1130
                                                ...                               
                clojure.core/binding-conveyor-fn/fn                 core.clj: 2038
             discljord.messaging.impl/step-agent/fn                 impl.clj: 1191
             discljord.messaging.impl/make-request!                 impl.clj: 1146
discljord.messaging.impl/make-request!/make-request                 impl.clj: 1141
                                                ...                               
                        discljord.messaging.impl/fn                 impl.clj:  943
clojure.lang.ExceptionInfo: Attempted to :edit-original-interaction-response with invalid parameters
       code: 10015
    message: "Unknown Webhook"

```

**Additional context**
Running through docker-compose V2.1
```
---
version: "2.1"
services:
  doplarr:
    image: lscr.io/linuxserver/doplarr
    container_name: doplarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=America/New_York
      - DISCORD__TOKEN=*REDACTED*
      - OVERSEERR__API=*REDACTED*
      - OVERSEERR__URL=http://*REDACTED*:5055
      - DISCORD__MAX_RESULTS=25 #optional
      - DISCORD__ROLE_ID=*REDACTED* #optional
      - DISCORD__REQUESTED_MSG_STYLE=:plain #optional
      - PARTIAL_SEASONS=true #optional
      - LOG_LEVEL=:info #optional
    volumes:
      - *REDACTED*:/config
    restart: unless-stopped
```
