### ISSUE TITLE
Bots cannot use this endpoint

### ISSUE THREAD

**Issue by darkspadez** [kiranshila/Doplarr#77]
**Describe the bug**
I seemed to have followed the instructions to the letter but running into an issue where on start up I get the following error and the role/role id set gets permission error.

**Logs**
```
2022-04-26T05:16:09.275Z 92edc4b5d72b INFO [doplarr.core:43] - Connected to guild
2022-04-26T05:16:09.410Z 92edc4b5d72b INFO [doplarr.core:49] - Setting role id. Reminder, even the server owner needs this role.
2022-04-26T05:16:09.486Z 92edc4b5d72b FATAL [doplarr.discord:165] - Error in setting command permissions
                               java.lang.Thread.run              Thread.java:  831
 java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  630
  java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1130
                                                ...                               
                clojure.core/binding-conveyor-fn/fn                 core.clj: 2050
             discljord.messaging.impl/step-agent/fn                 impl.clj: 1191
             discljord.messaging.impl/make-request!                 impl.clj: 1146
discljord.messaging.impl/make-request!/make-request                 impl.clj: 1141
                                                ...                               
                        discljord.messaging.impl/fn                 impl.clj:  924
clojure.lang.ExceptionInfo: Attempted to set invalid command permissions
       code: 20001
    message: "Bots cannot use this endpoint"
```

URL used:
`https://discord.com/api/oauth2/authorize?client_id=HIDDEN&permissions=0&scope=applications.commands%20bot`

docker compose:
```
doplarr:
    container_name: doplarr
    image: lscr.io/linuxserver/doplarr
    restart: unless-stopped
    environment:
      - PUID=${UID_VAL}
      - PGID=${GID_VAL}
      - TZ=${TIMEZONE_VAL}
      - DISCORD__TOKEN=1
      - OVERSEERR__API=1
      - OVERSEERR__URL=http://172.19.0.26:5055
      - DISCORD__ROLE_ID=1
      - OVERSEERR__DEFAULT_ID=1
    volumes:
      - /opt/doplarr/config:/config
```

**Additional context**
I feel like I am missing a step or something and probably something stupid on my end so I apologize in advance.
