### ISSUE TITLE
"The application did not respond" While searching for a request

### ISSUE THREAD

**Issue by draxxy9** [kiranshila/Doplarr#91]
**Describe the bug**
While searching for movies using a full title (i.e. "Deadpool 2"), Doplarr shows "The application did not respond" in response to the discord command, and provides a FATAL exception in the container logs.

Alternatively, while searching for "Deadpool" instead of "Deadpool 2", the application returns the drop-down to select a movie, where Deadpool 2 is available as an option.

**Screenshots**
*Broken:*
![image](https://user-images.githubusercontent.com/70827936/183236572-1b92c734-7595-492e-a418-cdabb026bd89.png)
![image](https://user-images.githubusercontent.com/70827936/183236548-eb981cb1-d22e-4fd8-b6dc-9818db4369da.png)
*Working:*
![image](https://user-images.githubusercontent.com/70827936/183236638-84e285c3-132a-4978-80c3-e31d90ee9966.png)
![image](https://user-images.githubusercontent.com/70827936/183236621-73250512-e887-4147-a0b4-2c9e6400f512.png)
![image](https://user-images.githubusercontent.com/70827936/183236647-03c327b4-0150-4f83-ab19-a19edd7c7fd0.png)

**Logs**
Please copy out the log in it's entirety, please make sure to hide any potential secrets/API keys - although they should be censored via the logging program.
```
2022-08-06T06:01:10.535Z 264f1a4420a2 INFO [doplarr.interaction-state-machine:28] - Performing search for movie "Deadpool 2"
2022-08-06T06:01:15.688Z 264f1a4420a2 FATAL [doplarr.interaction-state-machine:41] - Error in creating search responses
                               java.lang.Thread.run              Thread.java:  831
 java.util.concurrent.ThreadPoolExecutor$Worker.run  ThreadPoolExecutor.java:  630
  java.util.concurrent.ThreadPoolExecutor.runWorker  ThreadPoolExecutor.java: 1130
                                                ...
                clojure.core/binding-conveyor-fn/fn                 core.clj: 2050
             discljord.messaging.impl/step-agent/fn                 impl.clj: 1191
             discljord.messaging.impl/make-request!                 impl.clj: 1146
discljord.messaging.impl/make-request!/make-request                 impl.clj: 1141
                                                ...
                        discljord.messaging.impl/fn                 impl.clj:  943
clojure.lang.ExceptionInfo: Attempted to :edit-original-interaction-response with invalid parameters
       code: 10015
    message: "Unknown Webhook"
```

**Additional context**
I'm running a container with docker-ce-20.10.17 on CentOS Stream 8, kernel 4.18.0-394. My docker-compose.yml is:
```
---
version: "2.1"
services:
  doplarr:
    image: lscr.io/linuxserver/doplarr:latest
    container_name: doplarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Australia/Adelaide
      - DISCORD__TOKEN=############################
      - RADARR__API=############################
      - RADARR__URL=http://x.x.x.x:7878
      - SONARR__API=############################
      - SONARR__URL=http://x.x.x.x:8989
      - DISCORD__MAX_RESULTS=25
      - DISCORD__REQUESTED_MSG_STYLE=:plain
      - PARTIAL_SEASONS=true
      - LOG_LEVEL=:info
    volumes:
      - ./config:/config
    restart: unless-stopped
```
