### ISSUE TITLE
Constant "crashing", force restart of container helps but eventually stops

### ISSUE THREAD

**Issue by kaizensh** [kiranshila/Doplarr#96]
**Describe the bug**
Basically notice all the time in Discord that the bot is down, I'll go into SSH, restart the container and it comes back up. Then eventually down again.

**Logs**
Here is some docker logs where you will find the constant errors. I had the idea today to set a cronjob to restart doplarr every few hours as a bandaid but dont think that helped lol.
https://pastebin.com/9tfTnpEv

My current settings:
```
  discord_token: XXXXXXXXXXXXXX
  overseerr_url: "http://overseerr:5055"
  overseerr_api: XXXXXXXXXXXXXX
  radarr_api:
  radarr_url:
  sonarr_api:
  sonarr_url:
  discord_max_results: 10
  discord_role_id:
  discord_requested_msg_style: ":embed"
  sonarr_quality_profile:
  radarr_quality_profile:
  sonarr_language_profile:
  overseer_default_id: 19
  partial_seasons: "true"
  log_level: ":debug"
```

**Comment by kiranshila** [comment]
Well that's a new one. It seems the bot is having trouble hitting the discord websocket servers. I'll have to chew on that one.

**Comment by inrush-overload** [comment]
+1 same issue going on here. Frequently it doesn't log anything though, just have a dead container that, according to logs, looks like it should still be running

**Comment by seanmcbroom** [comment]
Any updates on this? I am facing the same issue

**Comment by Franscobec** [comment]
I have the same exact issue. Container just dies. The bot stays online, but does not accept commands. I need to restart the container once every hour which is extremely annoying.
It might not be exactly the same error as kaizensh's but it is the same issue.
Here's some screenshots:
![Screenshot_20230523_091826_Discord](https://github.com/kiranshila/Doplarr/assets/87747518/2baaa270-50c0-44cb-9ea5-6255ad3ab320)
![Screenshot_20230523_091840_Discord](https://github.com/kiranshila/Doplarr/assets/87747518/42c9ba76-0e44-44ab-8d75-5b2c4bb76975)
![Screenshot_20230523_092010_Samsung Internet](https://github.com/kiranshila/Doplarr/assets/87747518/6c50f370-4c5d-4d06-af75-f824c5dc1184)
![Screenshot_20230523_092029_Samsung Internet](https://github.com/kiranshila/Doplarr/assets/87747518/3b779dc9-4c92-449c-86a2-c0a6a56471d3)

**Comment by inrush-overload** [comment]
Fyi if you're running in docker, you can just set it to restart unless
stopped which has resolved the issue for me effectively. Every time it goes
down it just fires right back up and you don't realize any appreciable
service outage.

Looked like the crashes were due to discord being slow to respond (and the
app being too sensitive to those slow responses) causing it to error out

**Comment by Franscobec** [comment]
> Fyi if you're running in docker, you can just set it to restart unless stopped which has resolved the issue for me effectively. Every time it goes down it just fires right back up and you don't realize any appreciable service outage. Looked like the crashes were due to discord being slow to respond (and the app being too sensitive to those slow responses) causing it to error out

I do not have enough knowledge to do that, can you explain how I can do this ?
BTW my OS is TrueNAS Scale 22.12.2

**Comment by inrush-overload** [comment]
Sorry bud, I'm not familiar enough with TrueNAS Scale to walk you through.
Generally in Docker it will look like "--restart unless-stopped ", you
might have to add that in the truenas UI someplace, probably the same place
you define other command line arguments

**Comment by MFaroTusino** [comment]
+1 
This started happening for me this week after using this without issue since June 2022.

**Comment by HoustonDad** [comment]
This is an old bug, that's still getting hit. I've setup autoheal to fix this

```
  doplarr:
    image: "ghcr.io/kiranshila/doplarr:latest"
--SNIPPED--
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "docker logs seedbox-doplarr --since=5m 2>&1 | grep -q 'Connected to guild' || exit 1"]
      interval: 5m
      timeout: 10s
      retries: 3
      start_period: 2m
    labels:
      "autoheal" : "true"
  autoheal:
    image: willfarrell/autoheal
    container_name: autoheal
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - /etc/localtime:/etc/localtime
    environment:
      - AUTOHEAL_INTERVAL=10
    restart: unless-stopped
```

I hope this helps someone else
